[config]

# For additional information, please see the METplus Users Guide.
# https://metplus.readthedocs.io/en/latest/Users_Guide

###
# Processes to run
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#process-list
###

PROCESS_LIST = SeriesAnalysis


###
# Field Info
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#field-info
###

# USER INPUT
# Note that MODEL can be a single or group of models 
# Individual models should have a definition of their name and number of ensemble members on approx line 8 of function_library.py
# MODEL_GROUPS should be defined in function_library.py approx line 15
# FIELD1 can be raw, anom, std_anom, clim_mean, clim_std, lower_tercile, middle_tercile, upper_tercile
# TIME_PERIOD can be monthly or seasonal means
# Series_ANALYSIS_CUSTOM_LOOP_LIST loops through leads 1, 2, and 3 in this example.
MODEL = CFSandSFS
FIELD1 = raw
CLIM = 1994_2020
TIME_PERIOD = seasonal

# CUSTOM LOOP LIST 
# Taking the place of LEAD
SERIES_ANALYSIS_CUSTOM_LOOP_LIST = 01, 02, 03

LOOP_BY = INIT
INIT_TIME_FMT = %Y%m%d%H
INIT_BEG=1994110100
INIT_END=2020110100
INIT_INCREMENT = 1Y

FCST_SERIES_ANALYSIS_INPUT_TEMPLATE = {init?fmt=%Y}
OBS_SERIES_ANALYSIS_INPUT_TEMPLATE = {init?fmt=%Y}

FCST_SERIES_ANALYSIS_INPUT_DATATYPE = PYTHON_NUMPY
OBS_SERIES_ANALYSIS_INPUT_DATATYPE = PYTHON_NUMPY


FCST_VAR1_NAME = {CONFIG_DIR}/wrapper_combined.py 11 {custom?fmt=%s} tmp2m {CLIM} {MODEL} {INPUT_BASE}/model_applications/s2s_mme/SeriesAnalysis_fcstCFSandSFS_obsGHCNCAMS_SingleOrMultimodel/fcst {TIME_PERIOD} MET_PYTHON_INPUT_ARG {FIELD1}
FCST_VAR1_LEVELS = "(*,*)"
OBS_VAR1_NAME = {CONFIG_DIR}/wrapper_combined.py 11 {custom?fmt=%s} tmp2m {CLIM} obs {INPUT_BASE}/model_applications/s2s_mme/SeriesAnalysis_fcstCFSandSFS_obsGHCNCAMS_SingleOrMultimodel/obs {TIME_PERIOD} MET_PYTHON_INPUT_ARG {FIELD1}
OBS_VAR1_LEVELS = "(*,*)"

CONFIG_DIR = {PARM_BASE}/use_cases/model_applications/s2s_mme/SeriesAnalysis_fcstCFSandSFS_obsGHCNCAMS_SingleOrMultimodel

SERIES_ANALYSIS_VLD_THRESH = 0.7
SERIES_ANALYSIS_BLOCK_SIZE = 360*181
SERIES_ANALYSIS_CAT_THRESH = >=0.5

SERIES_ANALYSIS_OUTPUT_PREFIX = 

SERIES_ANALYSIS_RUNTIME_FREQ = RUN_ONCE

SERIES_ANALYSIS_STAT_LIST = ME, MAE, RMSE, TOTAL, FBAR, OBAR

SERIES_ANALYSIS_ONCE_PER_FIELD = False

SERIES_ANALYSIS_OUTPUT_DIR = {OUTPUT_BASE}/SeriesAnalysis_fcstCFSandSFS_obsGHCNCAMS_SingleOrMultimodel
SERIES_ANALYSIS_OUTPUT_TEMPLATE = Bias_SeriesAnalysis_tmp2m_{FIELD1}_{MODEL}_IC11_Lead{custom?fmt=%s}{TIME_PERIOD}_{CLIM}.nc

