[config]

# Documentation for this use case can be found at
# https://metplus.readthedocs.io/en/latest/generated/met_tool_wrapper/RMWAnalysis/RMWAnalysis.html

# For additional information, please see the METplus Users Guide.
# https://metplus.readthedocs.io/en/latest/Users_Guide

###
# Processes to run
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#process-list
###

PROCESS_LIST = RMWAnalysis


###
# Time Info
# LOOP_BY options are INIT, VALID, RETRO, and REALTIME
# If set to INIT or RETRO:
#   INIT_TIME_FMT, INIT_BEG, INIT_END, and INIT_INCREMENT must also be set
# If set to VALID or REALTIME:
#   VALID_TIME_FMT, VALID_BEG, VALID_END, and VALID_INCREMENT must also be set
# LEAD_SEQ is the list of forecast leads to process
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#timing-control
###

RMW_ANALYSIS_RUNTIME_FREQ = RUN_ONCE_PER_INIT_OR_VALID

LOOP_BY = INIT
INIT_TIME_FMT = %Y%m%d%H
INIT_BEG=2005080700
INIT_END=2005080700
INIT_INCREMENT = 12H

LEAD_SEQ = 12, 9, 6


RMW_ANALYSIS_CUSTOM_LOOP_LIST =

###
# File I/O
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#directory-and-filename-template-info
###

RMW_ANALYSIS_INPUT_DIR = {INPUT_BASE}/met_test/data/sample_fcst
RMW_ANALYSIS_INPUT_TEMPLATE = {init?fmt=%Y%m%d%H}/wrfprs_ruc13_{lead?fmt=%2H}.tm00_G212

RMW_ANALYSIS_OUTPUT_DIR = {OUTPUT_BASE}/met_tool_wrapper/SeriesAnalysis
RMW_ANALYSIS_OUTPUT_TEMPLATE = {init?fmt=%Y%m%d%H}_sa.nc


###
# Field Info
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#field-info
###

DATA_VAR1_NAME = PRMSL
DATA_VAR2_NAME = TMP

###
# RMWAnalysis Settings
# https://metplus.readthedocs.io/en/latest/Users_Guide/wrappers.html#rmwanalysis
###

#LOG_RMW_ANALYSIS_VERBOSITY = 2

RMW_ANALYSIS_CONFIG_FILE = {PARM_BASE}/met_config/RMWAnalysisConfig_wrapped

#RMW_ANALYSIS_MODEL =

#RMW_ANALYSIS_BASIN =

#RMW_ANALYSIS_STORM_NAME =

#RMW_ANALYSIS_STORM_ID =

#RMW_ANALYSIS_CYCLONE =

#RMW_ANALYSIS_INIT_BEG =
#RMW_ANALYSIS_INIT_END =

#RMW_ANALYSIS_VALID_BEG =
#RMW_ANALYSIS_VALID_END =

#RMW_ANALYSIS_INIT_MASK =
#RMW_ANALYSIS_VALID_MASK =
