body:
- type: input
  attributes:
    description: "List the METplus software version being used, along with all relevant METplus component versions."
    label: "Software Version"
  validations:
    required: true
- type: textarea
  attributes:
    description: "Describe the plot generation issue encountered."
    label: "Text"
  validations:
    required: true
