[config]

# Processes to run
PROCESS_LIST = PointStat

# Time info
LOOP_BY = INIT
INIT_TIME_FMT = %Y%m%d%H
INIT_BEG = 2024030700
INIT_END = 2024030700
INIT_INCREMENT = 6H

LEAD_SEQ = 6

##########
# File I/O
##########

FCST_POINT_STAT_INPUT_DIR = {INPUT_BASE}/GFS_0.25
FCST_POINT_STAT_INPUT_TEMPLATE = {init?fmt=%Y%m%d%H}/gfs.0p25.{init?fmt=%Y%m%d%H}.f{lead?fmt=%3H}.grib2

OBS_POINT_STAT_INPUT_DIR = 
OBS_POINT_STAT_INPUT_TEMPLATE = PYTHON_NUMPY = /d1/personal/hertneky/nrl/parm/read_asos_ceil.py {INPUT_BASE}/metar/Surface_METAR_20240307_0000.nc

POINT_STAT_OUTPUT_DIR = {OUTPUT_BASE}/point_stat

LOG_MET_VERBOSITY = 3

############
# Field Info
############

MODEL = gfs
OBTYPE = ceil

#FCST_VAR1_NAME = PRES
#FCST_VAR1_LEVELS = L0
#FCST_VAR1_OPTIONS = GRIB2_ipdtmpl_index=9;GRIB2_ipdtmpl_val=212;
FCST_VAR1_NAME = LCDC
FCST_VAR1_LEVELS = L0
FCST_VAR1_OPTIONS = GRIB2_ipdtmpl_index=8;GRIB2_ipdtmpl_val=6;

#OBS_VAR1_NAME = low_cloud_base_altitude
#OBS_VAR1_LEVELS = L0
OBS_VAR1_NAME = low_cloud_area_fraction
OBS_VAR1_LEVELS = L0

#########################
# PointStat configuration
#########################

POINT_STAT_INTERP_TYPE_METHOD = BILIN
POINT_STAT_INTERP_TYPE_WIDTH = 2

POINT_STAT_OUTPUT_FLAG_CTC = STAT
POINT_STAT_OUTPUT_FLAG_CTS = STAT
POINT_STAT_OUTPUT_FLAG_CNT = STAT

POINT_STAT_REGRID_TO_GRID = NONE
POINT_STAT_REGRID_METHOD = BILIN
POINT_STAT_REGRID_WIDTH = 2

POINT_STAT_GRID = FULL

POINT_STAT_POLY =
POINT_STAT_STATION_ID =

POINT_STAT_MESSAGE_TYPE = ADPSFC

OBS_POINT_STAT_WINDOW_BEGIN = -1799
OBS_POINT_STAT_WINDOW_END = 1799
