name: metplus_v13.0_py3.14
channels:
  - conda-forge
dependencies:
  - python=3.14.0
  - python-dateutil=2.9.0.post0
  - matplotlib=3.10.8
  - scipy=1.17.1
  - xarray=2026.4.0
  - netcdf4=1.7.4
  - pyyaml=6.0.3
  - statsmodels
  - imageio=2.37.0
  - imutils=0.5.4
  - pint=0.25.3
  - metpy=1.7.1
  - pyngl
  - eofs=2.0.0
  - cmocean=4.0.3
  - xesmf
  - lxml=6.0.4
  - pymysql=1.1.2
  - pandas=3.0.2
  - h5py
  - cartopy=0.25.0
  - psutil
  - pytest=9.0.3
  - pytest-cov
  - numpy=2.4.3
  - scikit-learn>=1.8.0
  - libstdcxx-ng
  - libssh