[config]

# Documentation for this use case can be found at
# https://metplus.readthedocs.io/en/latest/generated/model_applications/land_surface/PointStat_fcstUFS_obsISMN_SoilMoistureTemp.html

# For additional information, please see the METplus Users Guide.
# https://metplus.readthedocs.io/en/latest/Users_Guide

###########################################################
# General METplus Wrappers Settings
###########################################################

LOG_LEVEL = DEBUG

############################################################
# Processes to run
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#process-list
############################################################

PROCESS_LIST = ASCII2NC,PointStat

############################################################
# Time Info
# LOOP_BY options are INIT, VALID, RETRO, and REALTIME
# If set to INIT or RETRO:
# INIT_TIME_FMT, INIT_BEG, INIT_END, and INIT_INCREMENT must also be set
# If set to VALID or REALTIME:
# VALID_TIME_FMT, VALID_BEG, VALID_END, and VALID_INCREMENT must also be set
# LEAD_SEQ is the list of forecast leads to process
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#timing-control
############################################################

LOOP_BY = VALID
VALID_BEG = 2020080512
VALID_END = 2020080512
VALID_INCREMENT = 6H
VALID_TIME_FMT = %Y%m%d%H
LEAD_SEQ = 60

############################################################
# ASCII2NC settings for processing GDAS observations
# https://metplus.readthedocs.io/en/latest/Users_Guide/wrappers.html#pb2nc
############################################################

ASCII2NC_INPUT_DIR = {INPUT_BASE}/model_applications/land_surface/PointStat_fcstUFS_obsISMN_SoilMoistureTemp/obs/ismn/HeadVals
ASCII2NC_INPUT_TEMPLATE = */*/*.stm
ASCII2NC_INPUT_FORMAT = ismn
ASCII2NC_OUTPUT_DIR = {OUTPUT_BASE}/ascii2nc
ASCII2NC_OUTPUT_TEMPLATE = {valid?fmt=%Y%m%d%H}_ismn.nc
LOG_ASCII2NC_VERBOSITY = 10

############################################################
# PointStat Settings
# https://metplus.readthedocs.io/en/latest/Users_Guide/wrappers.html#pointstat
############################################################

POINT_STAT_CONFIG_FILE = {PARM_BASE}/met_config/PointStatConfig_wrapped
POINT_STAT_MESSAGE_TYPE = ADPSFC
POINT_STAT_OUTPUT_DIR={OUTPUT_BASE}/point_stat
POINT_STAT_OUTPUT_FLAG_MPR = BOTH
FCST_POINT_STAT_INPUT_DIR = {INPUT_BASE}/model_applications/land_surface/PointStat_fcstUFS_obsISMN_SoilMoistureTemp/fcst
FCST_POINT_STAT_INPUT_TEMPLATE = {init?fmt=%Y%m%d%H}/{init?fmt=%Y%m%d%H}.f{lead?fmt=%3H}.grib2
OBS_POINT_STAT_INPUT_DIR = {ASCII2NC_OUTPUT_DIR}
OBS_POINT_STAT_INPUT_TEMPLATE = {ASCII2NC_OUTPUT_TEMPLATE}
OBS_POINT_STAT_WINDOW_BEGIN = -43200
OBS_POINT_STAT_WINDOW_END = 43200
LOG_POINT_STAT_VERBOSITY=10
POINT_STAT_MESSAGE_TYPE_GROUP_MAP={key="ISMN"; val="SNOTEL,iRON,USCRN";}
POINT_STAT_MESSAGE_TYPE=ISMN

############################################################
# Field Info
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#field-info
############################################################

#FCST_POINT_STAT_INPUT_TEMPLATE=PYTHON_NUMPY
#OBS_POINT_STAT_PYEMBED_DEBUG=False
FCST_VAR1_NAME = SOILW
FCST_VAR1_LEVELS = Z0-0.1
OBS_VAR1_NAME = SOILW 
OBS_VAR1_LEVELS = Z0-0.1
