#!/bin/bash

# get version, use develop or X+6.Y for MET_BRANCH
dockerfile_path=$(dirname $DOCKERFILE_PATH)/../../docs/version
if cat $dockerfile_path | egrep -q '[0-9.]+$'; then
    let major=$(cut -d '.' -f1 $dockerfile_path)+6
    minor=$(cut -d '.' -f2 $dockerfile_path )
    met_branch=$major"."$minor
else
    met_branch=develop
fi

docker build -t $IMAGE_NAME --build-arg SOURCE_BRANCH=$SOURCE_BRANCH --build-arg MET_BRANCH=$met_branch --build-arg DO_GIT_CLONE=true .
