#!/bin/bash

# get version, use develop or X+6.Y for MET_BRANCH
met_branch=`$(dirname $DOCKERFILE_PATH)/hooks/get_met_version`

echo $met_branch
docker build -t $IMAGE_NAME --build-arg SOURCE_BRANCH=$SOURCE_BRANCH --build-arg MET_BRANCH=$met_branch --build-arg DO_GIT_CLONE=true .
