export METPLUS_TEST_INPUT_BASE=${HOME}/data/METplus_Data
export METPLUS_TEST_OUTPUT_BASE=${HOME}/pytest
export METPLUS_TEST_MET_INSTALL_DIR=${HOME}/met/9.0-beta3
export METPLUS_TEST_TMP_DIR=${METPLUS_TEST_OUTPUT_BASE}/tmp

export METPLUS_TEST_EXE_WGRIB2=wgrib2
export METPLUS_TEST_EXE_CUT=cut
export METPLUS_TEST_EXE_TR=tr
export METPLUS_TEST_EXE_RM=rm
export METPLUS_TEST_EXE_NCAP2=ncap2
export METPLUS_TEST_EXE_CONVERT=convert
export METPLUS_TEST_EXE_NCDUMP=ncdump
export METPLUS_TEST_EXE_EGREP=egrep
