# Dockerfile to create conda environment used for use cases
# that don't require any additional packages

FROM conda/miniconda3-centos7

WORKDIR /scripts
COPY scripts/metplus_base_env.sh .

RUN conda update -y -n base -c defaults conda \
 && ./metplus_base_env.sh

RUN conda list --name metplus_base.v5 > /usr/local/envs/metplus_base.v5/environments.yml
