ARG METPLUS_ENV_TAG=gempak
ARG METPLUS_IMG_TAG=develop

FROM dtcenter/metplus-envs:${METPLUS_ENV_TAG} AS env

ARG METPLUS_IMG_TAG=develop
FROM dtcenter/metplus-dev:${METPLUS_IMG_TAG}

USER root

COPY --from=env /usr/lib/jvm /usr/lib/jvm/
COPY --from=env /etc/java-17-openjdk /etc/java-17-openjdk/
COPY --from=env /data/input/GempakToCF.jar /data/input/GempakToCF.jar

# add java executable to path
ENV PATH="/usr/lib/jvm/java-17-openjdk-amd64/bin:${PATH}"

USER metuser
