ARG METPLUS_ENV_TAG=cycloneplotter.v5
ARG METPLUS_IMG_TAG=develop

FROM dtcenter/metplus-envs:${METPLUS_ENV_TAG} AS env

ARG METPLUS_IMG_TAG=develop
FROM dtcenter/metplus-dev:${METPLUS_IMG_TAG}

RUN mkdir -p /usr/local/conda/envs && mkdir -p /usr/local/conda/bin
COPY --from=env /usr/local/conda/envs /usr/local/conda/envs/
COPY --from=env /usr/local/conda/bin/conda /usr/local/conda/bin/conda

COPY --from=env /root/.local/share/cartopy /root/.local/share/cartopy/

ARG METPLUS_GET_CHROME=false
RUN if [ "${METPLUS_GET_CHROME}" = "true" ]; then \
      echo "Installing Chrome dependencies" &&\
      apt-get update &&\
      apt-get install -y --no-install-recommends \
          libasound2 libatk-bridge2.0-0 libcairo2 libcups2 libgbm1 \
          libnss3 libpango-1.0-0 libxcomposite1 libxdamage1 \
          libxfixes3 libxkbcommon0 libxrandr2 && \
      apt-get clean; \
    fi

# run entrypoint script to set uid and gid for metplus_user to running user's values

ENTRYPOINT ["/usr/local/bin/user-entrypoint.sh"]
