ARG METPLUS_ENV_TAG=gfdl-tracker
ARG METPLUS_IMG_TAG=develop

FROM dtcenter/metplus-envs:${METPLUS_ENV_TAG} as env

ARG METPLUS_IMG_TAG=develop
FROM dtcenter/metplus-dev:${METPLUS_IMG_TAG}

RUN echo "export LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:/usr/lib/x86_64-linux-gnu:/lib64;" >> /root/.bashrc

COPY --from=env /lib64/libm* /lib64/
COPY --from=env /usr/lib/x86_64-linux-gnu/libg* /usr/lib/x86_64-linux-gnu/
COPY --from=env /usr/local/lib/libhdf5* /usr/local/lib/
COPY --from=env /usr/local/lib/libnetcdf.so.19* /usr/local/lib/
COPY --from=env /usr/local/lib/libnetcdff* /usr/local/lib/
COPY --from=env /standalone_gfdl-vortextracker_v3.9a_gcc/trk_exec/* /usr/local/bin/
