[config]

# Documentation for this use case can be found at
# https://metplus.readthedocs.io/en/latest/generated/model_applications/land/GridStat_fcstGFS_obsSMOPS_soilMoisture_Python.html

# For additional information, please see the METplus Users Guide.
# https://metplus.readthedocs.io/en/latest/Users_Guide

###
# Processes to run
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#process-list
###

PROCESS_LIST = GridStat, SeriesAnalysis

###
# Time Info
# LOOP_BY options are INIT, VALID, RETRO, and REALTIME
# If set to INIT or RETRO:
#   INIT_TIME_FMT, INIT_BEG, INIT_END, and INIT_INCREMENT must also be set
# If set to VALID or REALTIME:
#   VALID_TIME_FMT, VALID_BEG, VALID_END, and VALID_INCREMENT must also be set
# LEAD_SEQ is the list of forecast leads to process
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#timing-control
###

LOOP_BY = INIT
INIT_TIME_FMT = %Y%m%d%H
INIT_BEG=2020060700
INIT_END=2020060700
INIT_INCREMENT = 12H

LEAD_SEQ = 24


###
# File I/O
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#directory-and-filename-template-info
###

FCST_GRID_STAT_INPUT_DIR = {INPUT_BASE}/model_applications/land/GridStat_fcstGFS_obsSMOPS_soilMoisture_Python
FCST_GRID_STAT_INPUT_TEMPLATE = {init?fmt=%Y%m%d%H}.f{lead?fmt=%3H}.grib2

OBS_GRID_STAT_INPUT_DIR = 
OBS_GRID_STAT_INPUT_TEMPLATE = PYTHON_NUMPY

GRID_STAT_CLIMO_MEAN_INPUT_DIR =
GRID_STAT_CLIMO_MEAN_INPUT_TEMPLATE =

GRID_STAT_CLIMO_STDEV_INPUT_DIR =
GRID_STAT_CLIMO_STDEV_INPUT_TEMPLATE =

GRID_STAT_OUTPUT_DIR = {OUTPUT_BASE}/GridStat_fcstGFS_obsSMOPS_soilMoisture_Python/GridStat
#GRID_STAT_OUTPUT_TEMPLATE = {MODEL}_verify_{OBTYPE}_{valid?fmt=%Y%m%d%H}


###
# Field Info
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#field-info
###

MODEL = WRF
OBTYPE = SMOPS

GRID_STAT_ONCE_PER_FIELD = False

FCST_IS_PROB = false

FCST_VAR1_NAME = SOILW
FCST_VAR1_LEVELS = Z0-0.1

OBS_VAR1_NAME = {PARM_BASE}/use_cases/model_applications/land/GridStat_fcstGFS_obsSMOPS_soilMoisture_Python/read_SMOPS_data.py {INPUT_BASE}/model_applications/land/GridStat_fcstGFS_obsSMOPS_soilMoisture_Python/NPR_SMOPS_CMAP_D20200608.nc Blended_SM
OBS_VAR1_LEVELS = "(*,*)"


#LOG_GRID_STAT_VERBOSITY = 2

GRID_STAT_CONFIG_FILE = {PARM_BASE}/met_config/GridStatConfig_wrapped

GRID_STAT_REGRID_TO_GRID = OBS
GRID_STAT_REGRID_METHOD = BILIN
GRID_STAT_REGRID_WIDTH = 2
GRID_STAT_DESC = NA


GRID_STAT_OUTPUT_FLAG_CNT = STAT

GRID_STAT_NC_PAIRS_FLAG_LATLON = TRUE
GRID_STAT_NC_PAIRS_FLAG_RAW = TRUE
GRID_STAT_NC_PAIRS_FLAG_DIFF = TRUE
GRID_STAT_NC_PAIRS_FLAG_CLIMO = FALSE
GRID_STAT_NC_PAIRS_FLAG_APPLY_MASK = TRUE


GRID_STAT_MASK_POLY = {MET_INSTALL_DIR}/data/poly/CONUS.poly


SERIES_ANALYSIS_RUNTIME_FREQ = RUN_ONCE_PER_INIT_OR_VALID
SERIES_ANALYSIS_RUN_ONCE_PER_STORM_ID = False
FCST_SERIES_ANALYSIS_INPUT_DIR = {FCST_GRID_STAT_INPUT_DIR}
FCST_SERIES_ANALYSIS_INPUT_TEMPLATE = {FCST_GRID_STAT_INPUT_TEMPLATE}

OBS_SERIES_ANALYSIS_INPUT_DIR = {FCST_GRID_STAT_INPUT_DIR}
OBS_SERIES_ANALYSIS_INPUT_TEMPLATE = NPR_SMOPS_CMAP_D{valid?fmt=%Y%m%d}.nc 
OBS_SERIES_ANALYSIS_INPUT_DATATYPE = PYTHON_NUMPY

SERIES_ANALYSIS_OUTPUT_DIR = {OUTPUT_BASE}/GridStat_fcstGFS_obsSMOPS_soilMoisture_Python/SeriesAnalysis
SERIES_ANALYSIS_OUTPUT_TEMPLATE = valid_{valid?fmt=%Y%m%d%H}_cnt_output.nc

SERIES_ANALYSIS_REGRID_TO_GRID = OBS
SERIES_ANALYSIS_REGRID_METHOD = BILIN

SERIES_ANALYSIS_OUTPUT_STATS_CNT = ME, MAE, RMSE, MBIAS, FBAR, OBAR

SERIES_ANALYSIS_MASK_POLY = {MET_INSTALL_DIR}/data/poly/CONUS.poly
SERIES_ANALYSIS_BLOCK_SIZE = 0
