MAINTAINER George McCabe <mccabe@ucar.edu>

ENV CASE_DIR /data
RUN mkdir -p ${CASE_DIR} \
 && chown -R metplususer:metplususers ${CASE_DIR}
 USER metplususer
 #
 RUN curl -SL https://github.com/NCAR/METplus/releases/download/v3.0/sample_data-medium_range-3.0.tgz | tar -xzC ${CASE_DIR} \
  && chmod 6775 ${CASE_DIR}
  #
  VOLUME $CASE_DIR
  USER root
  CMD ["true"]