# Constant variables used throughout the METplus wrappers source code

# dictionary used by get_wrapper_name function to easily convert wrapper
# name in many formats to the correct name of the wrapper class
LOWER_TO_WRAPPER_NAME = {
    'ascii2nc': 'ASCII2NC',
    'cycloneplotter': 'CyclonePlotter',
    'ensemblestat': 'EnsembleStat',
    'example': 'Example',
    'extracttiles': 'ExtractTiles',
    'gempaktocf': 'GempakToCF',
    'genvxmask': 'GenVxMask',
    'genensprod': 'GenEnsProd',
    'gfdltracker': 'GFDLTracker',
    'griddiag': 'GridDiag',
    'gridstat': 'GridStat',
    'ioda2nc': 'IODA2NC',
    'makeplots': 'MakePlots',
    'metdbload': 'METDbLoad',
    'mode': 'MODE',
    'mtd': 'MTD',
    'modetimedomain': 'MTD',
    'pb2nc': 'PB2NC',
    'pcpcombine': 'PCPCombine',
    'plotdataplane': 'PlotDataPlane',
    'plotpointobs': 'PlotPointObs',
    'point2grid': 'Point2Grid',
    'pointtogrid': 'Point2Grid',
    'pointstat': 'PointStat',
    'pyembedingest': 'PyEmbedIngest',
    'regriddataplane': 'RegridDataPlane',
    'seriesanalysis': 'SeriesAnalysis',
    'statanalysis': 'StatAnalysis',
    'tcgen': 'TCGen',
    'tcpairs': 'TCPairs',
    'tcrmw': 'TCRMW',
    'tcstat': 'TCStat',
    'tcmprplotter': 'TCMPRPlotter',
    'usage': 'Usage',
    'userscript': 'UserScript',
}

# supported file extensions that will automatically be uncompressed
COMPRESSION_EXTENSIONS = [
    '.gz',
    '.bz2',
    '.zip',
]

# Keywords of valid types of Python Embedding in MET tools
PYTHON_EMBEDDING_TYPES = [
    'PYTHON_NUMPY',
    'PYTHON_XARRAY',
    'PYTHON_PANDAS',
]

# types of climatology values that should be checked and set
CLIMO_TYPES = [
    'MEAN',
    'STDEV',
]

# comparison operators that the MET tools support
# key is an operator and value is the alphabetic equivalent
VALID_COMPARISONS = {
    '>=': 'ge',
    '>': 'gt',
    '==': 'eq',
    '!=': 'ne',
    '<=': 'le',
    '<': 'lt',
}

# wrappers that do not run shell commands
# used to check that at least one command was generated if it should
NO_COMMAND_WRAPPERS = (
    'Example',
    'CyclonePlotter',
)

# configuration variables that are specific to a given run
# these are copied from [config] to [runtime] at the
# end of the run so they will not be read if the final
# config file is passed back into METplus but they will
# still be available to review
RUNTIME_CONFS = [
    'RUN_ID',
    'CLOCK_TIME',
    'METPLUS_VERSION',
    'MET_INSTALL_DIR',
    'CONFIG_INPUT',
    'METPLUS_CONF',
    'TMP_DIR',
    'STAGING_DIR',
    'FILE_LISTS_DIR',
    'CONVERT',
    'GEMPAKTOCF_JAR',
    'GFDL_TRACKER_EXEC',
    'INPUT_MUST_EXIST',
    'USER_SHELL',
    'DO_NOT_RUN_EXE',
    'SCRUB_STAGING_DIR',
    'MET_BIN_DIR',
]

# datetime year month day (YYYYMMDD) notation
YMD = '%Y%m%d'

# datetime year month day hour minute second (YYYYMMDD_HHMMSS) notation
YMD_HMS = '%Y%m%d_%H%M%S'

# missing data value used to check if integer values are not set
# we often check for None if a variable is not set, but 0 and None
# have the same result in a test. 0 may be a valid integer value
MISSING_DATA_VALUE = -9999

# key is the name of the depreacted variable that is no longer allowed in any config files
# value is a dictionary containing information about what to do with the deprecated config
# 'sec' is the section of the config file where the replacement resides, i.e. config, dir,
#     filename_templates
# 'alt' is the alternative name for the deprecated config. this can be a single variable name or
#     text to describe multiple variables or how to handle it. Set to None to tell the user to
#     just remove the variable
# 'copy' is an optional item (defaults to True). set this to False if one cannot simply replace
#     the deprecated config variable name with the value in 'alt'
# 'req' is an optional item (defaults to True). this to False to report a warning for the
#     deprecated config and allow execution to continue. this is generally no longer used
#     because we are requiring users to update the config files. if used, the developer must
#     modify the code to handle both variables accordingly
DEPRECATED_DICT = {
    'LOOP_BY_INIT': {'sec': 'config', 'alt': 'LOOP_BY', 'copy': False},
    'PREPBUFR_DIR_REGEX': {'sec': 'regex_pattern', 'alt': None},
    'PREPBUFR_FILE_REGEX': {'sec': 'regex_pattern', 'alt': None},
    'OBS_INPUT_DIR_REGEX': {'sec': 'regex_pattern',
                            'alt': 'OBS_POINT_STAT_INPUT_DIR', 'copy': False},
    'FCST_INPUT_DIR_REGEX': {'sec': 'regex_pattern',
                             'alt': 'FCST_POINT_STAT_INPUT_DIR',
                             'copy': False},
    'FCST_INPUT_FILE_REGEX':
        {'sec': 'regex_pattern', 'alt': 'FCST_POINT_STAT_INPUT_TEMPLATE',
         'copy': False},
    'OBS_INPUT_FILE_REGEX': {'sec': 'regex_pattern',
                             'alt': 'OBS_POINT_STAT_INPUT_TEMPLATE',
                             'copy': False},
    'PREPBUFR_DATA_DIR': {'sec': 'config', 'alt': 'PB2NC_INPUT_DIR'},
    'PREPBUFR_MODEL_DIR_NAME': {'sec': 'config', 'alt': 'PB2NC_INPUT_DIR',
                                'copy': False},
    'OBS_INPUT_FILE_TMPL':
        {'sec': 'config', 'alt': 'OBS_POINT_STAT_INPUT_TEMPLATE'},
    'FCST_INPUT_FILE_TMPL':
        {'sec': 'config', 'alt': 'FCST_POINT_STAT_INPUT_TEMPLATE'},
    'NC_FILE_TMPL': {'sec': 'config',
                     'alt': 'PB2NC_OUTPUT_TEMPLATE'},
    'FCST_INPUT_DIR': {'sec': 'config', 'alt': 'FCST_POINT_STAT_INPUT_DIR'},
    'OBS_INPUT_DIR': {'sec': 'config', 'alt': 'OBS_POINT_STAT_INPUT_DIR'},
    'REGRID_TO_GRID': {'sec': 'config', 'alt': 'POINT_STAT_REGRID_TO_GRID'},
    'FCST_HR_START': {'sec': 'config', 'alt': 'LEAD_SEQ', 'copy': False},
    'FCST_HR_END': {'sec': 'config', 'alt': 'LEAD_SEQ', 'copy': False},
    'FCST_HR_INTERVAL': {'sec': 'config', 'alt': 'LEAD_SEQ', 'copy': False},
    'START_DATE': {'sec': 'config', 'alt': 'INIT_BEG or VALID_BEG',
                   'copy': False},
    'END_DATE': {'sec': 'config', 'alt': 'INIT_END or VALID_END',
                 'copy': False},
    'INTERVAL_TIME': {'sec': 'config',
                      'alt': 'INIT_INCREMENT or VALID_INCREMENT',
                      'copy': False},
    'BEG_TIME': {'sec': 'config', 'alt': 'INIT_BEG or VALID_BEG',
                 'copy': False},
    'END_TIME': {'sec': 'config', 'alt': 'INIT_END or VALID_END',
                 'copy': False},
    'START_HOUR': {'sec': 'config', 'alt': 'INIT_BEG or VALID_BEG',
                   'copy': False},
    'END_HOUR': {'sec': 'config', 'alt': 'INIT_END or VALID_END',
                 'copy': False},
    'OBS_BUFR_VAR_LIST': {'sec': 'config', 'alt': 'PB2NC_OBS_BUFR_VAR_LIST'},
    'TIME_SUMMARY_FLAG': {'sec': 'config', 'alt': 'PB2NC_TIME_SUMMARY_FLAG'},
    'TIME_SUMMARY_BEG': {'sec': 'config', 'alt': 'PB2NC_TIME_SUMMARY_BEG'},
    'TIME_SUMMARY_END': {'sec': 'config', 'alt': 'PB2NC_TIME_SUMMARY_END'},
    'TIME_SUMMARY_VAR_NAMES': {'sec': 'config',
                               'alt': 'PB2NC_TIME_SUMMARY_VAR_NAMES'},
    'TIME_SUMMARY_TYPE': {'sec': 'config', 'alt': 'PB2NC_TIME_SUMMARY_TYPE'},
    'OVERWRITE_NC_OUTPUT': {'sec': 'config',
                            'alt': 'PB2NC_SKIP_IF_OUTPUT_EXISTS',
                            'copy': False},
    'VERTICAL_LOCATION': {'sec': 'config', 'alt': 'PB2NC_VERTICAL_LOCATION'},
    'VERIFICATION_GRID': {'sec': 'config',
                          'alt': 'REGRID_DATA_PLANE_VERIF_GRID'},
    'WINDOW_RANGE_BEG': {'sec': 'config', 'alt': 'OBS_WINDOW_BEGIN'},
    'WINDOW_RANGE_END': {'sec': 'config', 'alt': 'OBS_WINDOW_END'},
    'OBS_EXACT_VALID_TIME':
        {'sec': 'config', 'alt': 'OBS_WINDOW_BEGIN and OBS_WINDOW_END',
         'copy': False},
    'FCST_EXACT_VALID_TIME':
        {'sec': 'config', 'alt': 'FCST_WINDOW_BEGIN and FCST_WINDOW_END',
         'copy': False},
    'PCP_COMBINE_METHOD':
        {'sec': 'config',
         'alt': 'FCST_PCP_COMBINE_METHOD and/or OBS_PCP_COMBINE_METHOD',
         'copy': False},
    'FHR_BEG': {'sec': 'config', 'alt': 'LEAD_SEQ', 'copy': False},
    'FHR_END': {'sec': 'config', 'alt': 'LEAD_SEQ', 'copy': False},
    'FHR_INC': {'sec': 'config', 'alt': 'LEAD_SEQ', 'copy': False},
    'FHR_GROUP_BEG': {'sec': 'config', 'alt': 'LEAD_SEQ_[N]', 'copy': False},
    'FHR_GROUP_END': {'sec': 'config', 'alt': 'LEAD_SEQ_[N]', 'copy': False},
    'FHR_GROUP_LABELS': {'sec': 'config', 'alt': 'LEAD_SEQ_[N]_LABEL',
                         'copy': False},
    'CYCLONE_OUT_DIR': {'sec': 'config', 'alt': 'CYCLONE_OUTPUT_DIR'},
    'ENSEMBLE_STAT_OUT_DIR': {'sec': 'config', 'alt': 'ENSEMBLE_STAT_OUTPUT_DIR'},
    'EXTRACT_OUT_DIR': {'sec': 'config', 'alt': 'EXTRACT_TILES_OUTPUT_DIR'},
    'GRID_STAT_OUT_DIR': {'sec': 'config', 'alt': 'GRID_STAT_OUTPUT_DIR'},
    'MODE_OUT_DIR': {'sec': 'config', 'alt': 'MODE_OUTPUT_DIR'},
    'MTD_OUT_DIR': {'sec': 'config', 'alt': 'MTD_OUTPUT_DIR'},
    'SERIES_INIT_OUT_DIR': {'sec': 'config', 'alt': 'SERIES_ANALYSIS_OUTPUT_DIR'},
    'SERIES_LEAD_OUT_DIR': {'sec': 'config', 'alt': 'SERIES_ANALYSIS_OUTPUT_DIR'},
    'SERIES_INIT_FILTERED_OUT_DIR':
        {'sec': 'config', 'alt': 'SERIES_ANALYSIS_FILTERED_OUTPUT_DIR'},
    'SERIES_LEAD_FILTERED_OUT_DIR':
        {'sec': 'config', 'alt': 'SERIES_ANALYSIS_FILTERED_OUTPUT_DIR'},
    'STAT_ANALYSIS_OUT_DIR':
        {'sec': 'config', 'alt': 'STAT_ANALYSIS_OUTPUT_DIR'},
    'TCMPR_PLOT_OUT_DIR': {'sec': 'config', 'alt': 'TCMPR_PLOT_OUTPUT_DIR'},
    'FCST_MIN_FORECAST': {'sec': 'config', 'alt': 'LEAD_SEQ_MIN'},
    'FCST_MAX_FORECAST': {'sec': 'config', 'alt': 'LEAD_SEQ_MAX'},
    'OBS_MIN_FORECAST': {'sec': 'config', 'alt': 'OBS_PCP_COMBINE_MIN_LEAD'},
    'OBS_MAX_FORECAST': {'sec': 'config', 'alt': 'OBS_PCP_COMBINE_MAX_LEAD'},
    'FCST_INIT_INTERVAL': {'sec': 'config', 'alt': None},
    'OBS_INIT_INTERVAL': {'sec': 'config', 'alt': None},
    'FCST_DATA_INTERVAL': {'sec': '', 'alt': 'FCST_PCP_COMBINE_DATA_INTERVAL'},
    'OBS_DATA_INTERVAL': {'sec': '', 'alt': 'OBS_PCP_COMBINE_DATA_INTERVAL'},
    'FCST_IS_DAILY_FILE': {'sec': '', 'alt': 'FCST_PCP_COMBINE_IS_DAILY_FILE'},
    'OBS_IS_DAILY_FILE': {'sec': '', 'alt': 'OBS_PCP_COMBINE_IS_DAILY_FILE'},
    'FCST_TIMES_PER_FILE': {'sec': '',
                            'alt': 'FCST_PCP_COMBINE_TIMES_PER_FILE'},
    'OBS_TIMES_PER_FILE': {'sec': '', 'alt': 'OBS_PCP_COMBINE_TIMES_PER_FILE'},
    'FCST_LEVEL': {'sec': '', 'alt': 'FCST_PCP_COMBINE_INPUT_ACCUMS',
                   'copy': False},
    'OBS_LEVEL': {'sec': '', 'alt': 'OBS_PCP_COMBINE_INPUT_ACCUMS',
                  'copy': False},
    'MODE_FCST_CONV_RADIUS': {'sec': 'config', 'alt': 'FCST_MODE_CONV_RADIUS'},
    'MODE_FCST_CONV_THRESH': {'sec': 'config', 'alt': 'FCST_MODE_CONV_THRESH'},
    'MODE_FCST_MERGE_FLAG': {'sec': 'config', 'alt': 'FCST_MODE_MERGE_FLAG'},
    'MODE_FCST_MERGE_THRESH': {'sec': 'config',
                               'alt': 'FCST_MODE_MERGE_THRESH'},
    'MODE_OBS_CONV_RADIUS': {'sec': 'config', 'alt': 'OBS_MODE_CONV_RADIUS'},
    'MODE_OBS_CONV_THRESH': {'sec': 'config', 'alt': 'OBS_MODE_CONV_THRESH'},
    'MODE_OBS_MERGE_FLAG': {'sec': 'config', 'alt': 'OBS_MODE_MERGE_FLAG'},
    'MODE_OBS_MERGE_THRESH': {'sec': 'config', 'alt': 'OBS_MODE_MERGE_THRESH'},
    'MTD_FCST_CONV_RADIUS': {'sec': 'config', 'alt': 'FCST_MTD_CONV_RADIUS'},
    'MTD_FCST_CONV_THRESH': {'sec': 'config', 'alt': 'FCST_MTD_CONV_THRESH'},
    'MTD_OBS_CONV_RADIUS': {'sec': 'config', 'alt': 'OBS_MTD_CONV_RADIUS'},
    'MTD_OBS_CONV_THRESH': {'sec': 'config', 'alt': 'OBS_MTD_CONV_THRESH'},
    'RM_EXE': {'sec': 'exe', 'alt': 'RM'},
    'CUT_EXE': {'sec': 'exe', 'alt': 'CUT'},
    'TR_EXE': {'sec': 'exe', 'alt': 'TR'},
    'NCAP2_EXE': {'sec': 'exe', 'alt': 'NCAP2'},
    'CONVERT_EXE': {'sec': 'exe', 'alt': 'CONVERT'},
    'NCDUMP_EXE': {'sec': 'exe', 'alt': 'NCDUMP'},
    'EGREP_EXE': {'sec': 'exe', 'alt': 'EGREP'},
    'ADECK_TRACK_DATA_DIR': {'sec': 'config', 'alt': 'TC_PAIRS_ADECK_INPUT_DIR'},
    'BDECK_TRACK_DATA_DIR': {'sec': 'config', 'alt': 'TC_PAIRS_BDECK_INPUT_DIR'},
    'MISSING_VAL_TO_REPLACE': {'sec': 'config',
                               'alt': 'TC_PAIRS_MISSING_VAL_TO_REPLACE'},
    'MISSING_VAL': {'sec': 'config', 'alt': 'TC_PAIRS_MISSING_VAL'},
    'TRACK_DATA_SUBDIR_MOD': {'sec': 'config', 'alt': None},
    'ADECK_FILE_PREFIX': {'sec': 'config', 'alt': 'TC_PAIRS_ADECK_TEMPLATE',
                          'copy': False},
    'BDECK_FILE_PREFIX': {'sec': 'config', 'alt': 'TC_PAIRS_BDECK_TEMPLATE',
                          'copy': False},
    'TOP_LEVEL_DIRS': {'sec': 'config', 'alt': 'TC_PAIRS_READ_ALL_FILES'},
    'TC_PAIRS_DIR': {'sec': 'config', 'alt': 'TC_PAIRS_OUTPUT_DIR'},
    'CYCLONE': {'sec': 'config', 'alt': 'TC_PAIRS_CYCLONE'},
    'STORM_ID': {'sec': 'config', 'alt': 'TC_PAIRS_STORM_ID'},
    'BASIN': {'sec': 'config', 'alt': 'TC_PAIRS_BASIN'},
    'STORM_NAME': {'sec': 'config', 'alt': 'TC_PAIRS_STORM_NAME'},
    'DLAND_FILE': {'sec': 'config', 'alt': 'TC_PAIRS_DLAND_FILE'},
    'TRACK_TYPE': {'sec': 'config', 'alt': 'TC_PAIRS_REFORMAT_DECK'},
    'FORECAST_TMPL': {'sec': 'config',
                      'alt': 'TC_PAIRS_ADECK_TEMPLATE'},
    'REFERENCE_TMPL': {'sec': 'config',
                       'alt': 'TC_PAIRS_BDECK_TEMPLATE'},
    'TRACK_DATA_MOD_FORCE_OVERWRITE':
        {'sec': 'config', 'alt': 'TC_PAIRS_SKIP_IF_REFORMAT_EXISTS',
         'copy': False},
    'TC_PAIRS_FORCE_OVERWRITE': {'sec': 'config',
                                 'alt': 'TC_PAIRS_SKIP_IF_OUTPUT_EXISTS',
                                 'copy': False},
    'GRID_STAT_CONFIG': {'sec': 'config', 'alt': 'GRID_STAT_CONFIG_FILE'},
    'MODE_CONFIG': {'sec': 'config', 'alt': 'MODE_CONFIG_FILE'},
    'FCST_PCP_COMBINE_INPUT_LEVEL': {'sec': 'config',
                                     'alt': 'FCST_PCP_COMBINE_INPUT_ACCUMS'},
    'OBS_PCP_COMBINE_INPUT_LEVEL': {'sec': 'config',
                                    'alt': 'OBS_PCP_COMBINE_INPUT_ACCUMS'},
    'TIME_METHOD': {'sec': 'config', 'alt': 'LOOP_BY', 'copy': False},
    'MODEL_DATA_DIR': {'sec': 'config', 'alt': 'EXTRACT_TILES_GRID_INPUT_DIR'},
    'STAT_LIST': {'sec': 'config', 'alt': 'SERIES_ANALYSIS_STAT_LIST'},
    'NLAT': {'sec': 'config', 'alt': 'EXTRACT_TILES_NLAT'},
    'NLON': {'sec': 'config', 'alt': 'EXTRACT_TILES_NLON'},
    'DLAT': {'sec': 'config', 'alt': 'EXTRACT_TILES_DLAT'},
    'DLON': {'sec': 'config', 'alt': 'EXTRACT_TILES_DLON'},
    'LON_ADJ': {'sec': 'config', 'alt': 'EXTRACT_TILES_LON_ADJ'},
    'LAT_ADJ': {'sec': 'config', 'alt': 'EXTRACT_TILES_LAT_ADJ'},
    'OVERWRITE_TRACK': {'sec': 'config',
                        'alt': 'EXTRACT_TILES_OVERWRITE_TRACK'},
    'BACKGROUND_MAP': {'sec': 'config',
                       'alt': 'SERIES_ANALYSIS_BACKGROUND_MAP'},
    'GFS_FCST_FILE_TMPL': {'sec': 'config',
                           'alt': 'FCST_EXTRACT_TILES_INPUT_TEMPLATE'},
    'GFS_ANLY_FILE_TMPL': {'sec': 'config',
                           'alt': 'OBS_EXTRACT_TILES_INPUT_TEMPLATE'},
    'SERIES_BY_LEAD_FILTERED_OUTPUT_DIR': {'sec': 'config',
                                           'alt': 'SERIES_ANALYSIS_FILTERED_OUTPUT_DIR'},
    'SERIES_BY_INIT_FILTERED_OUTPUT_DIR': {'sec': 'config',
                                           'alt': 'SERIES_ANALYSIS_FILTERED_OUTPUT_DIR'},
    'SERIES_BY_LEAD_OUTPUT_DIR': {'sec': 'config',
                                  'alt': 'SERIES_ANALYSIS_OUTPUT_DIR'},
    'SERIES_BY_INIT_OUTPUT_DIR': {'sec': 'config',
                                  'alt': 'SERIES_ANALYSIS_OUTPUT_DIR'},
    'SERIES_BY_LEAD_GROUP_FCSTS': {'sec': 'config',
                                   'alt': 'SERIES_ANALYSIS_GROUP_FCSTS'},
    'SERIES_ANALYSIS_BY_LEAD_CONFIG_FILE': {'sec': 'config',
                                            'alt': 'SERIES_ANALYSIS_CONFIG_FILE'},
    'SERIES_ANALYSIS_BY_INIT_CONFIG_FILE': {'sec': 'config',
                                            'alt': 'SERIES_ANALYSIS_CONFIG_FILE'},
    'ENSEMBLE_STAT_MET_OBS_ERROR_TABLE': {'sec': 'config',
                                          'alt': 'ENSEMBLE_STAT_MET_OBS_ERR_TABLE'},
    'VAR_LIST': {'sec': 'config',
                 'alt': 'BOTH_VAR<n>_NAME BOTH_VAR<n>_LEVELS or SERIES_ANALYSIS_VAR_LIST',
                 'copy': False},
    'SERIES_ANALYSIS_VAR_LIST': {'sec': 'config',
                                 'alt': 'BOTH_VAR<n>_NAME BOTH_VAR<n>_LEVELS',
                                 'copy': False},
    'EXTRACT_TILES_VAR_LIST': {'sec': 'config', 'alt': ''},
    'STAT_ANALYSIS_LOOKIN_DIR': {'sec': 'config',
                                 'alt': 'MODEL1_STAT_ANALYSIS_LOOKIN_DIR'},
    'VALID_HOUR_METHOD': {'sec': 'config', 'alt': None},
    'VALID_HOUR_BEG': {'sec': 'config', 'alt': None},
    'VALID_HOUR_END': {'sec': 'config', 'alt': None},
    'VALID_HOUR_INCREMENT': {'sec': 'config', 'alt': None},
    'INIT_HOUR_METHOD': {'sec': 'config', 'alt': None},
    'INIT_HOUR_BEG': {'sec': 'config', 'alt': None},
    'INIT_HOUR_END': {'sec': 'config', 'alt': None},
    'INIT_HOUR_INCREMENT': {'sec': 'config', 'alt': None},
    'STAT_ANALYSIS_CONFIG': {'sec': 'config',
                             'alt': 'STAT_ANALYSIS_CONFIG_FILE'},
    'JOB_NAME': {'sec': 'config', 'alt': 'STAT_ANALYSIS_JOB_NAME'},
    'JOB_ARGS': {'sec': 'config', 'alt': 'STAT_ANALYSIS_JOB_ARGS'},
    'FCST_LEAD': {'sec': 'config', 'alt': 'FCST_LEAD_LIST'},
    'FCST_VAR_NAME': {'sec': 'config', 'alt': 'FCST_VAR_LIST'},
    'FCST_VAR_LEVEL': {'sec': 'config', 'alt': 'FCST_VAR_LEVEL_LIST'},
    'OBS_VAR_NAME': {'sec': 'config', 'alt': 'OBS_VAR_LIST'},
    'OBS_VAR_LEVEL': {'sec': 'config', 'alt': 'OBS_VAR_LEVEL_LIST'},
    'REGION': {'sec': 'config', 'alt': 'VX_MASK_LIST'},
    'INTERP': {'sec': 'config', 'alt': 'INTERP_LIST'},
    'INTERP_PTS': {'sec': 'config', 'alt': 'INTERP_PTS_LIST'},
    'CONV_THRESH': {'sec': 'config', 'alt': 'CONV_THRESH_LIST'},
    'FCST_THRESH': {'sec': 'config', 'alt': 'FCST_THRESH_LIST'},
    'LINE_TYPE': {'sec': 'config', 'alt': 'LINE_TYPE_LIST'},
    'STAT_ANALYSIS_DUMP_ROW_TMPL': {'sec': 'config',
                                    'alt': 'STAT_ANALYSIS_DUMP_ROW_TEMPLATE'},
    'STAT_ANALYSIS_OUT_STAT_TMPL': {'sec': 'config',
                                    'alt': 'STAT_ANALYSIS_OUT_STAT_TEMPLATE'},
    'PLOTTING_SCRIPTS_DIR': {'sec': 'config', 'alt': 'MAKE_PLOTS_SCRIPTS_DIR'},
    'STAT_FILES_INPUT_DIR': {'sec': 'config', 'alt': 'MAKE_PLOTS_INPUT_DIR'},
    'PLOTTING_OUTPUT_DIR': {'sec': 'config', 'alt': 'MAKE_PLOTS_OUTPUT_DIR'},
    'VERIF_CASE': {'sec': 'config', 'alt': 'MAKE_PLOTS_VERIF_CASE'},
    'VERIF_TYPE': {'sec': 'config', 'alt': 'MAKE_PLOTS_VERIF_TYPE'},
    'PLOT_TIME': {'sec': 'config', 'alt': 'DATE_TIME'},
    'MODEL<n>_NAME': {'sec': 'config', 'alt': 'MODEL<n>'},
    'MODEL<n>_OBS_NAME': {'sec': 'config', 'alt': 'MODEL<n>_OBTYPE'},
    'MODEL<n>_STAT_DIR': {'sec': 'config',
                          'alt': 'MODEL<n>_STAT_ANALYSIS_LOOKIN_DIR'},
    'MODEL<n>_NAME_ON_PLOT': {'sec': 'config',
                              'alt': 'MODEL<n>_REFERENCE_NAME'},
    'REGION_LIST': {'sec': 'config', 'alt': 'VX_MASK_LIST'},
    'PLOT_STATS_LIST': {'sec': 'config', 'alt': 'MAKE_PLOT_STATS_LIST'},
    'CI_METHOD': {'sec': 'config', 'alt': 'MAKE_PLOTS_CI_METHOD'},
    'VERIF_GRID': {'sec': 'config', 'alt': 'MAKE_PLOTS_VERIF_GRID'},
    'EVENT_EQUALIZATION': {'sec': 'config',
                           'alt': 'MAKE_PLOTS_EVENT_EQUALIZATION'},
    'MTD_CONFIG': {'sec': 'config', 'alt': 'MTD_CONFIG_FILE'},
    'CLIMO_GRID_STAT_INPUT_DIR': {'sec': 'config',
                                  'alt': 'GRID_STAT_CLIMO_MEAN_INPUT_DIR'},
    'CLIMO_GRID_STAT_INPUT_TEMPLATE': {'sec': 'config',
                                       'alt': 'GRID_STAT_CLIMO_MEAN_INPUT_TEMPLATE'},
    'CLIMO_POINT_STAT_INPUT_DIR': {'sec': 'config',
                                   'alt': 'POINT_STAT_CLIMO_MEAN_INPUT_DIR'},
    'CLIMO_POINT_STAT_INPUT_TEMPLATE': {'sec': 'config',
                                        'alt': 'POINT_STAT_CLIMO_MEAN_INPUT_TEMPLATE'},
    'GEMPAKTOCF_CLASSPATH': {'sec': 'exe', 'alt': 'GEMPAKTOCF_JAR',
                             'copy': False},
    'CUSTOM_INGEST_<n>_OUTPUT_DIR': {'sec': 'config',
                                     'alt': 'PY_EMBED_INGEST_<n>_OUTPUT_DIR'},
    'CUSTOM_INGEST_<n>_OUTPUT_TEMPLATE': {'sec': 'config',
                                          'alt': 'PY_EMBED_INGEST_<n>_OUTPUT_TEMPLATE'},
    'CUSTOM_INGEST_<n>_OUTPUT_GRID': {'sec': 'config',
                                      'alt': 'PY_EMBED_INGEST_<n>_OUTPUT_GRID'},
    'CUSTOM_INGEST_<n>_SCRIPT': {'sec': 'config',
                                 'alt': 'PY_EMBED_INGEST_<n>_SCRIPT'},
    'CUSTOM_INGEST_<n>_TYPE': {'sec': 'config',
                               'alt': 'PY_EMBED_INGEST_<n>_TYPE'},
    'TC_STAT_RUN_VIA': {'sec': 'config', 'alt': 'TC_STAT_CONFIG_FILE',
                        'copy': False},
    'TC_STAT_CMD_LINE_JOB': {'sec': 'config', 'alt': 'TC_STAT_JOB_ARGS'},
    'TC_STAT_JOBS_LIST': {'sec': 'config', 'alt': 'TC_STAT_JOB_ARGS'},
    'EXTRACT_TILES_OVERWRITE_TRACK': {'sec': 'config',
                                      'alt': 'EXTRACT_TILES_SKIP_IF_OUTPUT_EXISTS',
                                      'copy': False},
    'EXTRACT_TILES_PAIRS_INPUT_DIR': {'sec': 'config',
                                      'alt': 'EXTRACT_TILES_STAT_INPUT_DIR',
                                      'copy': False},
    'EXTRACT_TILES_FILTERED_OUTPUT_TEMPLATE': {'sec': 'filename_template',
                                               'alt': 'EXTRACT_TILES_STAT_INPUT_TEMPLATE', },
    'EXTRACT_TILES_GRID_INPUT_DIR': {'sec': 'config',
                                     'alt': 'FCST_EXTRACT_TILES_INPUT_DIR'
                                            'and '
                                            'OBS_EXTRACT_TILES_INPUT_DIR',
                                     'copy': False},
    'SERIES_ANALYSIS_FILTER_OPTS': {'sec': 'config',
                                    'alt': 'TC_STAT_JOB_ARGS',
                                    'copy': False},
    'SERIES_ANALYSIS_INPUT_DIR': {'sec': 'config',
                                  'alt': 'FCST_SERIES_ANALYSIS_INPUT_DIR '
                                         'and '
                                         'OBS_SERIES_ANALYSIS_INPUT_DIR'},
    'FCST_SERIES_ANALYSIS_TILE_INPUT_TEMPLATE': {'sec': 'config',
                                                 'alt': 'FCST_SERIES_ANALYSIS_INPUT_TEMPLATE '},
    'OBS_SERIES_ANALYSIS_TILE_INPUT_TEMPLATE': {'sec': 'config',
                                                'alt': 'OBS_SERIES_ANALYSIS_INPUT_TEMPLATE '},
    'EXTRACT_TILES_STAT_INPUT_DIR': {'sec': 'config',
                                     'alt': 'EXTRACT_TILES_TC_STAT_INPUT_DIR', },
    'EXTRACT_TILES_STAT_INPUT_TEMPLATE': {'sec': 'config',
                                          'alt': 'EXTRACT_TILES_TC_STAT_INPUT_TEMPLATE', },
    'SERIES_ANALYSIS_STAT_INPUT_DIR': {'sec': 'config',
                                       'alt': 'SERIES_ANALYSIS_TC_STAT_INPUT_DIR', },
    'SERIES_ANALYSIS_STAT_INPUT_TEMPLATE': {'sec': 'config',
                                            'alt': 'SERIES_ANALYSIS_TC_STAT_INPUT_TEMPLATE', },
}

# template       '' : {'sec' : '', 'alt' : '', 'copy': True},