[config]

FCST_ZARR_STORE = /scratch3/BMC/hmtb/Daniel.Abdi/forecasts-reshrrr-diffusion-gfs/reshrrr_predictions_mem1.zarr
FCST_ZARR_VAR = T2M
FCST_ZARR_DIMS = time,lead,y,x

FCST_ZARR_TIME_VAR = time
FCST_ZARR_LEAD_VAR = lead_time
FCST_ZARR_LEVEL_VAR = level
FCST_ZARR_LAT_VAR = latitude
FCST_ZARR_LON_VAR = longitude

FCST_TIME_RANGE = 11
FCST_LEAD_RANGE = 1
#FCST_X_RANGE = 0
#FCST_Y_RANGE = 0
#FCST_LEVEL_INDEX = 11
#FCST_LEVEL_RANGE = 0,2
