name: "Run Use Cases"
description: "Run METplus Use Cases"
author: "mccabe@ucar.edu"

inputs:
  categories:
    description: 'Use case category or categories to run (separate by comma)'
    required: true
  only_run_new:
    description: 'If true, only run use cases that have :NEW at the end'
    required: false
    default: false

runs:
  if: ${{ !inputs.only_run_new || endsWith(inputs.categories, ":NEW") }}
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.categories }}
    - ${{ inputs.only_run_new }}
