ARG METPLUS_ENV_TAG=1.0

FROM dtcenter/metplus-environments:${METPLUS_ENV_TAG}

ARG METPLUS_IMAGE_TAG=dtcenter/metplus:develop

FROM ${METPLUS_IMAGE_TAG}
COPY --from=0 /usr/local/envs /usr/local/envs/

