ARG METPLUS_ENV_TAG=metplus_base
ARG METPLUS_IMG_TAG=xesmf

FROM dtcenter/metplus-envs:${METPLUS_ENV_TAG} as env

RUN ls /usr/local/envs

ARG METPLUS_IMG_TAG=xesmf

FROM dtcenter/metplus-dev:${METPLUS_IMG_TAG}

COPY --from=env /usr/local/envs /usr/local/envs/
