ARG METPLUS_ENV_TAG=metplus_base

FROM dtcenter/metplus-envs:${METPLUS_ENV_TAG} as env

RUN ls /usr/local/envs

ARG METPLUS_IMAGE_TAG=develop

FROM dtcenter/metplus-dev:${METPLUS_IMAGE_TAG}

COPY --from=env /usr/local/envs /usr/local/envs/
