[config]

# Documentation for this use case can be found at
# https://metplus.readthedocs.io/en/latest/generated/model_applications/sfc/GridStat_fcstSFSGSL_obsERA_SoilMoisture.html

# For additional information, please see the METplus Users Guide.
# https://metplus.readthedocs.io/en/latest/Users_Guide

###
# Processes to run
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#process-list
###

PROCESS_LIST = GridStat


###
# Time Info
# LOOP_BY options are INIT, VALID, RETRO, and REALTIME
# If set to INIT or RETRO:
#   INIT_TIME_FMT, INIT_BEG, INIT_END, and INIT_INCREMENT must also be set
# If set to VALID or REALTIME:
#   VALID_TIME_FMT, VALID_BEG, VALID_END, and VALID_INCREMENT must also be set
# LEAD_SEQ is the list of forecast leads to process
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#timing-control
###

LOOP_BY = VALID
VALID_TIME_FMT = %Y%m%d%H
VALID_BEG = 1991060100
VALID_END = 2020060100
VALID_INCREMENT = 12m
LOG_LEVEL = DEBUG

###
# File I/O
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#directory-and-filename-template-info
###

FCST_GRID_STAT_INPUT_TEMPLATE = PYTHON_NUMPY

OBS_GRID_STAT_INPUT_DIR = {INPUT_BASE}/model_applications/sfs/GridStat_fcstSFSGSL_obsERA_SoilMoisture/ERA5
OBS_GRID_STAT_INPUT_TEMPLATE = ERA5.soilm1m.1x1.1991-2020.mon.nc

GRID_STAT_OUTPUT_DIR = {OUTPUT_BASE}/model_applications/sfc/GridStat_fcstSFSGSL_obsERA_SoilMoisture
GRID_STAT_OUTPUT_TEMPLATE = {valid?fmt=%Y%m%d%H}


###
# Field Info
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#field-info
###


MODEL = SFS-GSL
OBTYPE = ERA5

#FCST_VAR1_NAME = /d1/personal/biswas/CPC-SFS/SoilMoisture/codes/sfs_gsl_model_wrapper.py {INPUT_BASE}/model_applications/sfs/GridStat_fcstSFSGSL_obsERA_SoilMoisture/SFS_GSL/SFS_GSL.soilm1m.{valid?fmt=%Y%m}.fcst.nc {valid?fmt=%2m} {valid?fmt=%Y}
FCST_VAR1_NAME = {PARM_BASE}/use_cases/model_applications/s2s/GridStat_fcstSFSGSL_obsERA_SoilMoisture/sfs_gsl_model_wrapper.py {INPUT_BASE}/model_applications/sfs/GridStat_fcstSFSGSL_obsERA_SoilMoisture/SFS_GSL/SFS_GSL.soilm1m.{valid?fmt=%Y%m}.fcst.nc {valid?fmt=%2m} {valid?fmt=%Y}
FCST_VAR1_THRESH = gt1.0, gt2.0, >SFP25, >SFP50, >SFP75 

OBS_VAR1_NAME = soilm1m
OBS_VAR1_LEVELS =  "({valid?fmt=%Y%m%d_%H%M%S},*,*)"
OBS_GRID_STAT_FILE_TYPE = NETCDF_NCCF

OBS_VAR1_THRESH = gt1.0, gt2.0, >SOP25, >SOP50, >SOP75 


###
# GridStat Settings
# https://metplus.readthedocs.io/en/latest/Users_Guide/wrappers.html#gridstat
###

#GRID_STAT_MASK_POLY = mask_na.poly
GRID_STAT_VERIFICATION_MASK_TEMPLATE =
  {INPUT_BASE}/model_applications/sfs/GridStat_fcstSFSGSL_obsERA_SoilMoisture/masks/CONUS.nc


GRID_STAT_OUTPUT_FLAG_FHO = BOTH
GRID_STAT_OUTPUT_FLAG_CTC = STAT
GRID_STAT_OUTPUT_FLAG_CTS = STAT
GRID_STAT_OUTPUT_FLAG_CNT = STAT
GRID_STAT_OUTPUT_FLAG_SL1L2 = STAT
GRID_STAT_OUTPUT_FLAG_ECLV = NONE

GRID_STAT_REGRID_TO_GRID = OBS
GRID_STAT_REGRID_METHOD = BILIN
GRID_STAT_REGRID_WIDTH = 2
GRID_STAT_REGRID_SHAPE = SQUARE

GRID_STAT_ONCE_PER_FIELD = False

GRID_STAT_OUTPUT_PREFIX = {MODEL}_vs_{OBTYPE}
