[config]

# Documentation for this use case can be found at
# https://metplus.readthedocs.io/en/latest/generated/model_applications/s2s_mid_lat/UserScript_fcstGFS_obsERA_Blocking.html

# For additional information, please see the METplus Users Guide.
# https://metplus.readthedocs.io/en/latest/Users_Guide

###
# Processes to run
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#process-list
###

PROCESS_LIST = PcpCombine(obs_mean_stdev)

###
# Time Info
# LOOP_BY options are INIT, VALID, RETRO, and REALTIME
# If set to INIT or RETRO:
#   INIT_TIME_FMT, INIT_BEG, INIT_END, and INIT_INCREMENT must also be set
# If set to VALID or REALTIME:
#   VALID_TIME_FMT, VALID_BEG, VALID_END, and VALID_INCREMENT must also be set
# LEAD_SEQ is the list of forecast leads to process
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#timing-control
###

LOG_LEVEL = DEBUG

LOOP_BY = VALID
VALID_TIME_FMT = %Y%m%d%H
VALID_BEG = 2020010100
VALID_END = 2020120100
VALID_INCREMENT = 1m
LEAD_SEQ = 0

###
# PCPCombine(obs_mean_stdev) Settings
# https://metplus.readthedocs.io/en/latest/Users_Guide/wrappers.html#pcpcombine
###

[obs_mean_stdev]

OBS_PCP_COMBINE_RUN = True

OBS_PCP_COMBINE_METHOD = DERIVE
OBS_PCP_COMBINE_STAT_LIST = mean,stdev

OBS_PCP_COMBINE_INPUT_ACCUMS = 1Y

OBS_PCP_COMBINE_INPUT_NAMES = SWVL1
OBS_PCP_COMBINE_INPUT_LEVELS = "({valid?fmt=%Y%m%d_%H%M%S},*,*)"

OBS_PCP_COMBINE_DERIVE_LOOKBACK = 30Y

OBS_PCP_COMBINE_INPUT_DIR = {INPUT_BASE}/biswas/SFS/ERA5_sfc
OBS_PCP_COMBINE_OUTPUT_DIR = {OUTPUT_BASE}/SoilMoisture

# Input ERA Interim
OBS_PCP_COMBINE_INPUT_TEMPLATE = e5.moda.an.sfc.128_039_swvl1.ll025sc.{valid?fmt=%Y}010100_{valid?fmt=%Y}120100.nc
OBS_PCP_COMBINE_OUTPUT_TEMPLATE = SoilMoisture_30year_{valid?fmt=%m}_mean_stdev.nc
