# Dockerfile to create conda environments used for use case tests

ARG METPLUS_ENV_VERSION=v5.1
ARG BASE_ENV=metplus_base.${METPLUS_ENV_VERSION}
FROM dtcenter/metplus-envs:${BASE_ENV}

ARG ENV_NAME
WORKDIR /scripts
COPY scripts/${ENV_NAME}_env.sh .

ARG METPLUS_ENV_VERSION=v5.1
ARG BASE_ENV=metplus_base.${METPLUS_ENV_VERSION}
RUN ./${ENV_NAME}_env.sh ${BASE_ENV}
