# Dockerfile to install conda

ARG DEBIAN_VERSION=10
FROM debian:${DEBIAN_VERSION}-slim

RUN apt update && apt install -y curl \
 && curl https://repo.anaconda.com/miniconda/Miniconda3-py310_22.11.1-1-Linux-x86_64.sh > /miniconda.sh \
 && bash /miniconda.sh -b -p /usr/local/conda \
 && /usr/local/conda/bin/conda update -y -n base -c conda-forge conda
