# Dockerfile to install conda

# Should match the OS used in https://github.com/dtcenter/METbaseimage
ARG DEBIAN_VERSION=12
FROM debian:${DEBIAN_VERSION}-slim

RUN apt update && apt install -y curl \
 && curl https://repo.anaconda.com/miniconda/Miniconda3-py311_23.5.2-0-Linux-x86_64.sh > /miniconda.sh \
 && bash /miniconda.sh -b -p /usr/local/conda \
 && /usr/local/conda/bin/conda update -y -n base -c conda-forge conda
