[config]

# Documentation for this use case can be found at
# https://metplus.readthedocs.io/en/latest/generated/met_tool_wrapper/DataIngest/DataIngest.html

# For additional information, please see the METplus Users Guide.
# https://metplus.readthedocs.io/en/latest/Users_Guide

###
# Processes to run
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#process-list
###

PROCESS_LIST = DataIngest


###
# Time Info
# LOOP_BY options are INIT, VALID, RETRO, and REALTIME
# If set to INIT or RETRO:
#   INIT_TIME_FMT, INIT_BEG, INIT_END, and INIT_INCREMENT must also be set
# If set to VALID or REALTIME:
#   VALID_TIME_FMT, VALID_BEG, VALID_END, and VALID_INCREMENT must also be set
# LEAD_SEQ is the list of forecast leads to process
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#timing-control
###

LOOP_BY = VALID
VALID_TIME_FMT = %Y%m%d%H
VALID_BEG=2022072000
VALID_END=2022072012
VALID_INCREMENT = 12H

LEAD_SEQ = 0


###
# File I/O
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#directory-and-filename-template-info
###

DATA_INGEST_SKIP_IF_OUTPUT_EXISTS = False

DATA_INGEST_1_INPUT_TEMPLATE = https://dtcenter.ucar.edu/dfiles/code/METplus/DataIngest_input/{valid?fmt=%Y/%m/%d}/point/metar/netcdf/{valid?fmt=%Y%m%d_%H%M}.gz
DATA_INGEST_1_OUTPUT_TEMPLATE = {OUTPUT_BASE}/data_ingest/madis_metar/{valid?fmt=%Y%m%d_%H%M}.nc
#DATA_INGEST_1_SKIP_IF_OUTPUT_EXISTS = False
DATA_INGEST_1_AUTO_DECOMPRESS = True
DATA_INGEST_1_USERNAME = anonymous
DATA_INGEST_1_PASSWORD = anonymous

DATA_INGEST_2_INPUT_TEMPLATE = https://dtcenter.ucar.edu/dfiles/code/METplus/DataIngest_input/radiation/surfrad/Boulder_CO/{valid?fmt=%Y}/tbl{valid?fmt=%y%j}.dat
DATA_INGEST_2_OUTPUT_TEMPLATE = {OUTPUT_BASE}/data_ingest/surfrad/tbl{valid?fmt=%Y%m%d}.dat
DATA_INGEST_2_SKIP_IF_OUTPUT_EXISTS = True
DATA_INGEST_2_AUTO_DECOMPRESS = True
#DATA_INGEST_2_USERNAME =
#DATA_INGEST_2_PASSWORD =
