export METPLUS_TEST_INPUT_BASE=/d1/METplus_Data
export METPLUS_TEST_GEMPAKTOCF_BIN=/d1/mccabe/bin/GempakToCF

export METPLUS_TEST_A_METPLUS_BASE=/d1/$USER/METplus.a
export METPLUS_TEST_A_OUTPUT_BASE=/d1/$USER/test-a
export METPLUS_TEST_A_MET_INSTALL_DIR=/usr/local/met-8.1.1

export METPLUS_TEST_B_METPLUS_BASE=/d1/$USER/METplus.b
export METPLUS_TEST_B_OUTPUT_BASE=/d1/$USER/test-b
export METPLUS_TEST_B_MET_INSTALL_DIR=/usr/local/met-8.1.1
