#!/bin/bash
curl -u "jprestop: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" -X POST           -H "Accept: application/vnd.github.v3+json"           -d '{"name": "priority: bold for release notes","#fc6A03": "f8de7e","description": "Issue should be bolded in release notes"}' 'https://api.github.com/repos/dtcenter/met/labels'
curl -u "jprestop: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" -X POST           -H "Accept: application/vnd.github.v3+json"           -d '{"name": "priority: bold for release notes","#fc6A03": "f8de7e","description": "Issue should be bolded in release notes"}' 'https://api.github.com/repos/dtcenter/metbaseimage/labels'
curl -u "jprestop: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" -X POST           -H "Accept: application/vnd.github.v3+json"           -d '{"name": "priority: bold for release notes","#fc6A03": "f8de7e","description": "Issue should be bolded in release notes"}' 'https://api.github.com/repos/dtcenter/metdataio/labels'
curl -u "jprestop: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" -X POST           -H "Accept: application/vnd.github.v3+json"           -d '{"name": "priority: bold for release notes","#fc6A03": "f8de7e","description": "Issue should be bolded in release notes"}' 'https://api.github.com/repos/dtcenter/metexpress/labels'
curl -u "jprestop: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" -X POST           -H "Accept: application/vnd.github.v3+json"           -d '{"name": "priority: bold for release notes","#fc6A03": "f8de7e","description": "Issue should be bolded in release notes"}' 'https://api.github.com/repos/dtcenter/metplotpy/labels'
curl -u "jprestop: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" -X POST           -H "Accept: application/vnd.github.v3+json"           -d '{"name": "priority: bold for release notes","#fc6A03": "f8de7e","description": "Issue should be bolded in release notes"}' 'https://api.github.com/repos/dtcenter/metplus-internal/labels'
curl -u "jprestop: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" -X POST           -H "Accept: application/vnd.github.v3+json"           -d '{"name": "priority: bold for release notes","#fc6A03": "f8de7e","description": "Issue should be bolded in release notes"}' 'https://api.github.com/repos/dtcenter/metplus/labels'
curl -u "jprestop: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" -X POST           -H "Accept: application/vnd.github.v3+json"           -d '{"name": "priority: bold for release notes","#fc6A03": "f8de7e","description": "Issue should be bolded in release notes"}' 'https://api.github.com/repos/dtcenter/metviewer/labels'
