"""
RMWAnalysis: Basic Use Case
===========================

met_tool_wrapper/RMWAnalysis/RMWAnalysis.conf

"""
##############################################################################
# Scientific Objective
# --------------------
#
# The RMW-Analysis tool analyzes a set of output files generated by the TC-RMW tool.


##############################################################################
# Datasets
# --------
#
# | **Data:** TC-RMW output
#
# | **Location:** All of the input data required for this use case can be found in the met_test sample data tarball. Click here to the METplus releases page and download sample data for the appropriate release: https://github.com/dtcenter/METplus/releases
# | This tarball should be unpacked into the directory that you will set the value of INPUT_BASE. See `Running METplus`_ section for more information.
# |

##############################################################################
# METplus Components
# ------------------
#
# This use case runs the METplus RMWAnalysis wrapper to analyze TC-RMW output.

##############################################################################
# METplus Workflow
# ----------------
#
# RMWAnalysis is the only tool called in this example. It processes the following
# run times:
#
# | **Init:** 2023
# |

##############################################################################
# METplus Configuration
# ---------------------
#
# parm/use_cases/met_tool_wrapper/RMWAnalysis/RMWAnalysis.conf
#
# .. highlight:: bash
# .. literalinclude:: ../../../../parm/use_cases/met_tool_wrapper/RMWAnalysis/RMWAnalysis.conf

##############################################################################
# MET Configuration
# -----------------
#
# .. note::
#     See the :ref:`RMWAnalysis MET Configuration<rmw-analysis-met-conf>`
#     section of the User's Guide for more information on the environment
#     variables used in the file below.
#
# parm/met_config/RMWAnalysisConfig_wrapped
#
# .. highlight:: bash
# .. literalinclude:: ../../../../parm/met_config/RMWAnalysisConfig_wrapped

##############################################################################
# Running METplus
# ---------------
#
# Provide the use case .conf configuration file to the run_metplus.py script.
#
# /path/to/METplus/parm/use_cases/met_tool_wrapper/RMWAnalysis/RMWAnalysis.conf
#
# See the :ref:`running-metplus` section of the System Configuration chapter
# for more details.

##############################################################################
# Expected Output
# ---------------
#
# A successful run will output the following both to the screen and to the logfile::
#
#   INFO: METplus has successfully finished running.
#
# Refer to the value set for **OUTPUT_BASE** to find where the output data was generated.
# Output for this use case will be found in rmw_analysis (relative to **OUTPUT_BASE**)
# and will contain the following files:
#
# * rmw_analysis_aal142023.nc
#

##############################################################################
# Keywords
# --------
#
# .. note::
#
#   * RMWAnalysisToolUseCase
#
#   Navigate to the :ref:`quick-search` page to discover other similar use cases.
#
#
#
# sphinx_gallery_thumbnail_path = '_static/met_tool_wrapper-RMWAnalysis.png'
#
