ARG METPLUS_BASE_REPO=metplus
ARG METPLUS_BASE_TAG

FROM dtcenter/${METPLUS_BASE_REPO}:${METPLUS_BASE_TAG}
LABEL org.opencontainers.image.authors="mccabe@ucar.edu"

ARG METDATAIO_VERSION
ARG METCALCPY_VERSION
ARG METPLOTPY_VERSION

# clone and install METplus Analysis Python packages
# Create non-root user for running the container

RUN git clone --branch "$METDATAIO_VERSION" https://github.com/dtcenter/METdataio \
    && pip install -r METdataio/requirements.txt && pip install METdataio/. \
    && git clone --branch "$METCALCPY_VERSION" https://github.com/dtcenter/METcalcpy \
    && pip install -r METcalcpy/requirements.txt && pip install METcalcpy/. \
    && git clone --branch "$METPLOTPY_VERSION" https://github.com/dtcenter/METplotpy \
    && pip install -r METplotpy/requirements.txt && pip install METplotpy/. &&\
  groupadd -r metplus && useradd -r -g metplus -u 1000 metplus

# Switch to non-root user
USER metplus

# Set working directory to the user workspace
WORKDIR /work
