FROM centos:7
MAINTAINER George McCabe <mccabe@ucar.edu>

ENV CASE_DIR /data/input/METplus_Data
RUN mkdir -p ${CASE_DIR}

RUN curl -SL https://github.com/NCAR/METplus/releases/download/v3.1-beta1/sample_data-met_tool_wrapper-3.1-beta1.2.tgz | tar -xzC ${CASE_DIR}

VOLUME $CASE_DIR
USER root
CMD ["true"]