[config]
# CI OVERRIDE for model_applications/s2s_soil_moisture/GridStat_fcstSFSGSL_obsERA5Land_SoilMoisture
# these settings can overrides the settings in the use case conf so they run in a reasonable amount
# of time in automation

# Specifically, we are only testing Series-Analysis for 3 valid times instead of the whole 30 year
# dataset

[sm_2d]
VALID_END = 1995060100
