name: Documentation
on:
  push:
    branches:
      - develop
      - feature_**
      - main_**
      - bugfix_**
    paths:
      - docs/**
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade sphinx sphinx-gallery sphinx_rtd_theme
          python -m pip install python-dateutil requests Pillow
      - name: Build Documentation
        run: ./.github/jobs/build_documentation.sh
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: METplus_documentation
          path: artifact/documentation
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: documentation_warnings.log
          path: artifact/doc_warnings.log
          if-no-files-found: ignore
