name: linkcheck
on:
  schedule:
    - cron: '0 6 * * 1'
  pull_request:
    paths:
      - 'docs/**'
  workflow_dispatch: {}

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtcenter/metplus-action-linkcheck@v1
        with:
          fail-on-broken-links: 'true'
          upload-artifact: 'true'
          install-package: 'true'