name: Create Release Docker Images

on:

  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      release_version:
        description: 'Comma-separated list of versions to build, e.g. "v6.0.0","v6.1.0"'
        default: '"v6.1.0"'
        required: true
        type: string
      update_latest:
        description: 'For "vX.Y.Z" versions, update the corresponding "X.Y-latest" images.'
        default: false
        required: true
        type: boolean

  schedule:
    - cron: "30 06 * * 0"

env:
  DOCKERHUB_BASE_REPO: dtcenter/metplus
  DOCKERHUB_ANALYSIS_REPO: dtcenter/metplus-analysis

jobs:

  define-matrix:
    name: Define Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-versions.outputs.matrix }}
      update_latest: ${{ steps.get-versions.outputs.update_latest }}

    steps:
      - name: Get versions to build 
        id: get-versions
        run: |
          if [[ ${{ github.event_name }} == 'schedule' ]]; then
            version_list="\"v6.0.0\",\"v6.1.0\""
            update_latest="true"
          elif [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            version_list=${{ toJSON(inputs.release_version) }}
            update_latest=${{ toJSON(inputs.update_latest) }}
          else
            version_list=\"${{ toJSON(github.ref_name) }}\"
            update_latest="true"
          fi
          echo "matrix={\"version\": [ ${version_list} ]}" >> $GITHUB_OUTPUT
          echo "update_latest=${update_latest}" >> $GITHUB_OUTPUT
 
  build_scan_and_push:
    name: Build, Scan, and Push Images
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.version }}
          path: ${{ matrix.version }}
          sparse-checkout: internal/scripts/docker
          sparse-checkout-cone-mode: false

      - uses: actions/checkout@v4
        with:
          ref: 'develop'
          path: 'develop'
          sparse-checkout: metplus/component_versions.py
          sparse-checkout-cone-mode: false

      - name: Set version without v prefix
        id: set-version
        run: |
          version="${{ matrix.version }}"
          echo "VERSION_NO_V=${version#v}" >> $GITHUB_ENV

      - name: Build Docker Images
        id: build_images
        run: .github/jobs/docker_build_metplus_images.sh
        env:
          SOURCE_BRANCH: ${{ matrix.version }}
          METPLUS_VERSION: ${{ env.VERSION_NO_V }}
          DOCKERHUB_BASE_REPO: ${{ env.DOCKERHUB_BASE_REPO }}
          DOCKERHUB_ANALYSIS_REPO: ${{ env.DOCKERHUB_ANALYSIS_REPO }}

      - name: Scan Docker Images
        id: security-scan
        continue-on-error: false
        uses: dtcenter/metplus-action-scan-docker-images@v1
        with:
          images: |
            [
              "${{ env.DOCKERHUB_BASE_REPO }}:${{ env.VERSION_NO_V }}",
              "${{ env.DOCKERHUB_ANALYSIS_REPO }}:${{ env.VERSION_NO_V }}"
            ]
          fail-on-critical: "true"
          log-artifact-name: 'security-scan-logs_${{ env.VERSION_NO_V }}'

      - name: Push Docker Images
        run: .github/jobs/docker_push_metplus_images.sh
        env:
          METPLUS_VERSION: ${{ env.VERSION_NO_V }}
          UPDATE_LATEST: ${{ fromJSON(needs.define-matrix.outputs.update_latest) }}
          DOCKERHUB_BASE_REPO: ${{ env.DOCKERHUB_BASE_REPO }}
          DOCKERHUB_ANALYSIS_REPO: ${{ env.DOCKERHUB_ANALYSIS_REPO }}
          DOCKER_USERNAME: 'dtcenter'
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
