name: Update Input Test Data
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to update (default develop)'

jobs:
  update_data_volumes:
    name: Update Data Volumes
    runs-on: ubuntu-latest
    steps:
      - uses: dtcenter/metplus-action-data-update@v2
        with:
          docker_name: ${{ secrets.DOCKER_USERNAME }}
          docker_pass: ${{ secrets.DOCKER_PASSWORD }}
          repo_name: ${{ github.repository }}
          data_prefix: sample_data
          branch_name: ${{ github.event.inputs.branch || 'develop' }}
          docker_data_dir: /data/input/METplus_Data
          data_repo_dev: metplus-data-dev
          data_repo_stable: metplus-data
          use_feature_data: true
          tag_max_pages: 15

