import pytest

import sys
import os
import shutil
from datetime import datetime, timedelta
from unittest import mock
from pathlib import Path
from netCDF4 import Dataset

# add METplus directory to path so the wrappers and utilities can be found
metplus_dir = str(Path(__file__).parents[3])
sys.path.insert(0, os.path.abspath(metplus_dir))

from metplus.util import config_metplus

output_base = os.environ.get("METPLUS_TEST_OUTPUT_BASE")
if not output_base:
    print("ERROR: METPLUS_TEST_OUTPUT_BASE must be set to a path to write")
    sys.exit(1)

try:
    test_output_dir = os.path.join(output_base, "test_output")
    if os.path.exists(test_output_dir):
        print(f"Removing test output dir: {test_output_dir}")
        shutil.rmtree(test_output_dir)

    if not os.path.exists(test_output_dir):
        print(f"Creating test output dir: {test_output_dir}")
        os.makedirs(test_output_dir)
except PermissionError:
    print(f"ERROR: Cannot write to $METPLUS_TEST_OUTPUT_BASE: {output_base}")
    sys.exit(2)

# used in tests like ioda2nc and ascii2nc to test runtime frequency options
# values correspond to missing, run, thresh, errors, allow_missing, runtime_freq
obs_to_nc_runtime_freq_test_params = [
        (16, 24, 0.3, 0, True, 'RUN_ONCE_FOR_EACH'),
        (16, 24, 0.7, 1, True, 'RUN_ONCE_FOR_EACH'),
        (16, 24, 0.3, 16, False, 'RUN_ONCE_FOR_EACH'),
        (2, 4, 0.4, 0, True, 'RUN_ONCE_PER_INIT_OR_VALID'),
        (2, 4, 0.6, 1, True, 'RUN_ONCE_PER_INIT_OR_VALID'),
        (2, 4, 0.6, 16, False, 'RUN_ONCE_PER_INIT_OR_VALID'),
        (2, 5, 0.4, 0, True, 'RUN_ONCE_PER_LEAD'),
        (2, 5, 0.7, 1, True, 'RUN_ONCE_PER_LEAD'),
        (2, 5, 0.4, 17, False, 'RUN_ONCE_PER_LEAD'),
        (0, 1, 0.4, 0, True, 'RUN_ONCE'),
        (0, 1, 0.4, 16, False, 'RUN_ONCE'),
    ]


# used in tests like grid_stat and wavelet_stat to test runtime frequency options
# values correspond to once_per_field, missing, run, thresh, errors, allow_missing
stat_runtime_freq_test_params = [
        (False, 6, 12, 0.5, 0, True),
        (False, 6, 12, 0.6, 1, True),
        (True, 12, 24, 0.5, 0, True),
        (True, 12, 24, 0.6, 1, True),
        (False, 6, 12, 0.5, 10, False),
        (True, 12, 24, 0.5, 20, False),
    ]

@pytest.fixture
def fcst_and_obs_data():
    fcst_name = 'APCP'
    fcst_level = 'A03'
    obs_name = 'APCP_03'
    obs_level = '"(*,*)"'

    inits = ['2005080700', '2005080712']
    time_fmt = '%Y%m%d%H'
    lead_hour = 12
    valids = []
    for init in inits:
        valid = datetime.strptime(init, time_fmt) + timedelta(hours=lead_hour)
        valid = valid.strftime(time_fmt)
        valids.append(valid)
    return fcst_name, fcst_level, obs_name, obs_level, inits, valids, lead_hour, time_fmt

@pytest.fixture(scope="session", autouse=True)
def custom_tmpdir():
    """! Set the default output location for temp files produced by pytest
    to METPLUS_TEST_OUTPUT_BASE env var. Causes default pytest fixtures,
    such as tmpdir_factory, to write temp files to this dir.

    A sub directory named 'pytest_tmp' is created to ensure there will never
    be name conflicts between files created by default pytest fixture and
    other methods for writing temp files.
    """
    original_var = os.environ.get("PYTEST_DEBUG_TEMPROOT", None)
    output_base = os.environ.get("METPLUS_TEST_OUTPUT_BASE")
    temp_base = os.path.join(output_base, "pytest_tmp")

    os.environ["PYTEST_DEBUG_TEMPROOT"] = temp_base
    if not os.path.exists(temp_base):
        os.mkdir(temp_base)
    yield
    # Restore original value, if existed
    if original_var:
        os.environ["PYTEST_DEBUG_TEMPROOT"] = original_var


@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """! This is used to capture the status of a test so the metplus_config
    fixture can remove output data from tests that pass.
    """
    # execute all other hooks to obtain the report object
    outcome = yield
    rep = outcome.get_result()

    # set a report attribute for each phase of a call, which can
    # be "setup", "call", "teardown"

    setattr(item, "rep_" + rep.when, rep)


@pytest.fixture()
def metplus_config(request):
    """! Create a METplus configuration object using only the minimum required
    settings found in minimum_pytest.conf. This fixture checks the result of
    the test it is used in and automatically removes the output that is
    generated by it unless the test fails. This makes it much easier to review
    the failed tests. To use this fixture, add metplus_config to the test
    function arguments and set a variable called config to metplus_config, e.g.
    config = metplus_config.

    This fixture wraps config.logger with a MagicMock object, allowing tests to
    assert the logger was called with a specific message. Logged output is still
    written to ${METPLUS_TEST_OUTPUT_BASE}/test_output/{RUN_ID}/logs/metplus.log 

    e.g.
    def test_example(metplus_config):
        config = metplus_config
        some_function(config)
        config.logger.info.assert_called_once_with("Info message")
        config.logger.error.assert_not_called()

    See documentation for unittest.mock for full functionality.
    """
    script_dir = os.path.dirname(__file__)
    args = [os.path.join(script_dir, "minimum_pytest.conf")]
    config = config_metplus.setup(args)

    # Set mock logger
    old_logger = config.logger
    config.logger = mock.MagicMock(wraps=old_logger)

    yield config
    
    if config.logger.error.call_args_list:
        err_msgs = [
                str(msg.args[0]) 
                for msg 
                in config.logger.error.call_args_list
                if len(msg.args) != 0]
        print("Tests raised the following errors:")
        print("\n".join(err_msgs))
    if config.logger.warning.call_args_list:
        warn_msgs = [
                str(msg.args[0])
                for msg
                in config.logger.warning.call_args_list
                if len(msg.args) != 0]
        print("\nTests raised the following warnings:")
        print("\n".join(warn_msgs))
    config.logger = old_logger
    # don't remove output base if test fails
    if request.node.rep_call.failed:
        return
    config_output_base = config.getdir("OUTPUT_BASE")
    if config_output_base and os.path.exists(config_output_base):
        shutil.rmtree(config_output_base)


@pytest.fixture(scope="function")
def metplus_config_files():
    """! Create a METplus configuration object using minimum_pytest.conf
    settings and any list of config files.The metplus_config fixture is
    preferred because it automatically cleans up the output files generated
    by the use case unless the test fails. To use this in a test, add
    metplus_config_files as an argument to the test function and pass in a list
    of config files to it. Example: config = metplus_config_files([my_file])
    """

    def read_configs(extra_configs):
        # Read in minimum pytest config file and any other extra configs
        script_dir = os.path.dirname(__file__)
        minimum_conf = os.path.join(script_dir, "minimum_pytest.conf")
        args = extra_configs.copy()
        args.insert(0, minimum_conf)
        config = config_metplus.setup(args)
        return config

    return read_configs


@pytest.fixture(scope="module")
def make_dummy_nc():
    return make_nc

def make_nc(tmp_path, lon, lat, z, data, variable='Temp', file_name='fake.nc', attributes=None, fill_value=-9999):
    """! Make a dummy netCDF file for use in tests. Populates a generic single
    variable netcdf is dimension, lat, lon, z.

    @param tmp_path directory to write this netCDF to.
    @param lon list of longitude values.
    @param lat list of latitude values.
    @param z list of pressure levels.
    @param data array of values with dimesions (lat, lon, z) 
    @param variable (optional) string name of variable, defualt 'Temp'
    @param file_name (optional) string name of file, defualt 'fake.nc'
    
    @returns path to netCDF file
    """
    file_name = tmp_path / file_name
    with Dataset(file_name, "w", format="NETCDF4") as rootgrp:
        # Some tools (i.e. diff_util) can't deal with groups,
        # so attach dimensions and variables to the root group.
        rootgrp.createDimension("lon", len(lon))
        rootgrp.createDimension("lat", len(lat))
        rootgrp.createDimension("z", len(z))
        rootgrp.createDimension("time", None)

        # create variables
        longitude = rootgrp.createVariable("Longitude", "f4", "lon")
        latitude = rootgrp.createVariable("Latitude", "f4", "lat")
        levels = rootgrp.createVariable("Levels", "i4", "z")
        temp = rootgrp.createVariable(variable, "f4", ("time", "lon", "lat", "z"), fill_value=fill_value)
        if attributes:
            for key, value in attributes.items():
                temp.setncattr(key, value)

        rootgrp.createVariable("Time", "i4", "time")

        longitude[:] = lon
        latitude[:] = lat
        levels[:] = z
        temp[0, :, :, :] = data

    return file_name


@pytest.fixture(scope="module")
def make_dummy_empty():
    return make_empty


def make_empty(tmp_path, file_name='fake.txt'):
    """!Make a dummy empty file for use in tests.

    @param tmp_path directory to write this empty file to.
    @param file_name (optional) string name of file, defualt 'fake.txt'
    @returns path to an empty file
    """
    file_path = tmp_path / file_name

    # Create parent directories if they don't exist
    file_path.parent.mkdir(parents=True, exist_ok=True)

    file_path.touch()
    return file_path


@pytest.fixture(scope="function")
def get_test_data_dir():
    """!Get path to directory containing test data.
    """
    def get_test_data_path(subdir=None):
        internal_tests_dir = os.path.abspath(
            os.path.join(os.path.dirname(__file__), os.pardir, 'data')
        )
        if subdir:
            internal_tests_dir = os.path.join(internal_tests_dir, subdir)
        return internal_tests_dir

    return get_test_data_path


@pytest.fixture(scope="function")
def compare_command_and_env_vars():
    def do_comparison(all_commands, expected_cmds, env_var_values, wrapper,
                      special_values=None):
        print(f"ALL COMMANDS: {all_commands}")
        assert len(all_commands) == len(expected_cmds)

        if hasattr(wrapper, 'WRAPPER_ENV_VAR_KEYS'):
            wrapper_env_var_keys = wrapper.WRAPPER_ENV_VAR_KEYS
        else:
            wrapper_env_var_keys = []
        missing_env = [item for item in env_var_values
                       if item not in wrapper_env_var_keys
                       and item != 'DIAG_ARG']
        env_var_keys = wrapper_env_var_keys + missing_env

        for (actual_cmd, env_vars), expected_cmd in zip(all_commands, expected_cmds):
            # ensure commands are generated as expected
            assert actual_cmd == expected_cmd

            # check that environment variables were set properly
            # including deprecated env vars (not in wrapper env var keys)
            for env_var_key in env_var_keys:
                print(f"ENV VAR: {env_var_key}")
                match = next((item for item in env_vars if
                              item.startswith(env_var_key)), None)
                assert match is not None
                value = match.split('=', 1)[1]
                if special_values is not None and env_var_key in special_values:
                    assert value == special_values[env_var_key]
                else:
                    assert value == env_var_values.get(env_var_key, '')

    return do_comparison


@pytest.fixture(scope="module")
def set_init_configs():
    def set_init_config_settings(config):
        config.set('config', 'LOOP_BY', 'INIT')
        config.set('config', 'INIT_TIME_FMT', '%Y%m%d%H')
        config.set('config', 'INIT_BEG', '2017051001')
        config.set('config', 'INIT_END', '2017051003')
        config.set('config', 'INIT_INCREMENT', '2H')
        config.set('config', 'LEAD_SEQ', '1,2,3,6,9,12')

    return set_init_config_settings


@pytest.fixture(scope="module")
def run_all_and_check_missing():
    def run_all_and_check_missing_run_error(wrapper, missing, run, errors):
        assert wrapper.is_ok

        all_cmds = wrapper.run_all_times()
        for cmd, _ in all_cmds:
            print(cmd)

        print(f'missing: {wrapper.missing_input_count} / {wrapper.run_count}, errors: {wrapper.errors}')
        assert wrapper.missing_input_count == missing
        assert wrapper.run_count == run
        assert wrapper.errors == errors

    return run_all_and_check_missing_run_error

@pytest.fixture(scope="module")
def check_warn_output_overwrite():
    def check_warn_output_overwrite_wrapper(wrapper, expected_warning, expected_path):
        if expected_warning:
            # Verify that a warning was logged
            assert wrapper.logger.warning.called

            # Extract and verify the warning message content
            # Using the same pattern as existing tests in the file
            last_msg = wrapper.logger.warning.call_args_list[-1][0][0]
            assert "Output has already been written" in last_msg
            assert expected_path in last_msg
        else:
            # Verify that no warning was logged for new files
            assert not wrapper.logger.warning.called

    return check_warn_output_overwrite_wrapper
