export METPLUS_TEST_INPUT_BASE=/d1/METplus_Data
export METPLUS_TEST_OUTPUT_BASE=/d1/${USER}/pytest
export METPLUS_TEST_MET_INSTALL_DIR=/usr/local/met-9.0
#export METPLUS_TEST_MET_INSTALL_DIR=/d1/CODE/MET/MET_releases/met-9.0_beta4
export METPLUS_TEST_TMP_DIR=${METPLUS_TEST_OUTPUT_BASE}/tmp
